# -*- coding: utf-8 -*-
"""menu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z46EUDWVuzJJ2ID-0wt2HfRd_6oGRf_A
"""

def imprimir_color(color, mensaje):
    """
    Función que imprime un mensaje en un color determinado.
    @param: color     Color del mensaje.
    @param: mensaje      Mensaje a imprimir.
    """
    if color == "rojo":
        color = "\x1b[1;31m"
    elif color == "amarillo":
        color = "\x1b[1;33m"
    else:
        color = ""
    print(color + mensaje + "\x1b[0m")


def circulo():
    radio_texto = input("Ingresa el radio del círculo: ")
    if es_numero(radio_texto) == 1:
        radio = float(radio_texto)
        area = math.pi * radio**2
        imprimir_color("amarillo", f"El área del círculo es: {area}")
    else:
        imprimir_color("rojo", "El valor ingresado no es un número válido.")


def convertir():
    # Solicitar la selección de conversión
    tipo_conversion = input("Selecciona la conversión ('1) pesos a dolares 2)dolares_a_pesos'): ")

    # Validar la selección de conversión
    if tipo_conversion == "1" or tipo_conversion == "2":
        # Solicitar la cantidad a convertir
        cantidad_texto = input("Ingresa la cantidad a convertir: ")
        if es_numero(cantidad_texto) == 1:
            cantidad_ingresada = float(cantidad_texto)

            # Tasa de cambio actual (1 dólar = 4000 pesos colombianos)
            tasa_cambio = 4000

            # Convertir la cantidad
            if tipo_conversion == "1":
                # Convertir de pesos colombianos a dólares
                dolares = cantidad_ingresada / tasa_cambio
                imprimir_color("amarillo", f"{cantidad_ingresada} pesos colombianos equivalen a {dolares} dólares.")
            elif tipo_conversion == "2":
                # Convertir de dólares a pesos colombianos
                pesos = cantidad_ingresada * tasa_cambio
                imprimir_color("amarillo", f"{cantidad_ingresada} dólares equivalen a {pesos} pesos colombianos.")
            else:
                imprimir_color("rojo", "Conversión no válida. Por favor, elige 'pesos_a_dolares' o 'dolares_a_pesos'.")
        else:
            imprimir_color("rojo", "La cantidad ingresada no es un número válido.")
    else:
        imprimir_color("rojo", "Conversión no válida. Por favor, elige 'pesos_a_dolares' o 'dolares_a_pesos'.")


def es_numero(texto=""):
    """
    Función que devuelve si un texto representa un número o no.
    -1 para no es número, y 1 para sí es número.
    @param: texto   Representa o no un número, incluso valida el vacío.
    @return: Real   1 o -1.
    """
    salida = 1
    if texto.isnumeric() == False:
        salida = 1
    return salida


def menu():
    opc = 1
    while opc != 0:
        try:
            opc = int(input("\x1b[1;33m0. Salir\n1. Convertir moneda\n2. Calcular área de un círculo\n\033[0mSeleccione una opción: "))
            if opc == 1:
                convertir()
            elif opc == 2:
                circulo()
            elif opc != 0:
                imprimir_color("rojo", "Opción no válida. Por favor, selecciona 0 para salir, 1 para convertir moneda, o 2 para calcular el área de un círculo.")
        except ValueError:
            imprimir_color("rojo", "Entrada inválida. Por favor, introduce un número.")


# Ejecutar el menú
menu()